### ISSUE TITLE
Mock Server

### ISSUE THREAD

**Issue by qyvlik** [188080501/JQNetwork#5]
我又来提需求了，这次是希望有一个Mock Server的支持。

实现一个服务器不是大问题，重点是如何实现 Mock 的各种 Rule 呢？

**Comment by 188080501** [comment]
这个我觉得可以有

**Comment by 188080501** [comment]
初期的话，我就得先做简单的字符串收发功能，你觉得呢

**Comment by qyvlik** [comment]
@188080501 可以的，最好是JSON格式的字符串。
试试配合 [GraphQL](http://www.jianshu.com/p/6721b66c5ac8)

**Comment by 188080501** [comment]
感觉随着开发的深入，做一个JSON字符串格式的mock服务器已经脱离初衷了，现在看应该不会再在这个JQNetwork里开发这个JSON字符串格式的mock服务器。

**Comment by qyvlik** [comment]
@188080501 这样啊。不过使用 [GraphQL](http://www.jianshu.com/p/6721b66c5ac8) 规范的Mock服务还是可以考虑的。
